# Default Terminal
set -g default-terminal xterm-256color
set -ga terminal-overrides ",alacritty:Tc"

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix


# Avoid ESC delay
set -s escape-time 0

# Enable vi mode
set -g mode-keys vi
set -g status-keys vi

# split panes using | and -
bind = split-window -h
bind - split-window -v
unbind '"'
unbind %

# reload config file
bind r source-file ~/.config/tmux/tmux.conf

# Start window and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Enable mouse mode
set -g mouse on

# don't rename windows automatically
set-option -g allow-rename off

# Recommended in lazy.nvim :checkhealth result
set-option -sa terminal-overrides ',xterm-256color:RGB'


